version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pair-trading-postgres
    environment:
      POSTGRES_DB: pair_trading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - pair-trading-network

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    container_name: pair-trading-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pair-trading-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pair-trading-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pair_trading
      - REDIS_URL=redis://redis:6379
      - J_QUANTS_API_KEY=${J_QUANTS_API_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - pair-trading-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pair-trading-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - pair-trading-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  pair-trading-network:
    driver: bridge
